### ISSUE TITLE
[feature] connect Teazy's OBS

### ISSUE THREAD

**Issue by cannawen** [cannawen/discord-moderator#16]

**Comment by tnnguyen13** [comment]
three different situations

1. canna, no teazy
2. teazy, no canna
3. canna and teazy - both obs connected
4. canna and teazy - canna obs connected only
5. canna and teazy - teazy obs connected only
6. canna and teazy - no obs connected

**Comment by tnnguyen13** [comment]
need to handle what happens when one person is offline and someone attempts to clip

**Comment by cannawen** [comment]
Instead of having the interface of obsClient like this:
```
export default {
  connectCanna,
  connectTeazy,
  disconnectCanna,
  disconnectTeazy,
  clipCanna,
  clipTeazy,
};

```

We can refactor it like Alex said to be `connect(constants.memberId.CANNA)` so we still only need to expose 3 functions, but pass in the memberId of who we are talking about 

We should also look into what error is actually being returned when Teazy's OBS websocket fails to connect

**Comment by cannawen** [comment]
On second thought it's a bit icky to have discord member IDs cross over into OBS territory. We could create OBS constants instead for Canna/Teazy ... but then why not just have two separate functions then. Maybe it's OK as is since it's only 2-ish OBSes

**Comment by cannawen** [comment]
It looks like it just takes ~2 minutes for the OBS websocket library to figure out that my stream OBS isn't running. Reverted back to an old version and it had the same behaviour. My Game OBS doesn't seem to experience that lag though, so, the code is probably fine as is?

**Comment by cannawen** [comment]
Closing, I think story is complete.
